name: Publish cekit
on:
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install CEKit
        uses: cekit/actions-setup-cekit@v1.1.7
      - name: Build CEKit image
        run: cekit --descriptor ./runtime-image/image.yaml build --dry-run docker
      - name: Check Image
        run: |
          cat target/image/Dockerfile
      - name: Push to new branch the output
        run: |
          cp -prf target/image konflux
          git checkout -b konflux
          git config --global user.email "rubendario.novelli@gmail.com"
          git config --global user.name "Ruben Novelli"          
          git add konflux
          git commit -m "Sync files"
          git push origin konflux
