name: Publish cekit
on:
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install CEKit
        uses: cekit/actions-setup-cekit@v1.1.7
      - name: Build CEKit image
        run: cekit --descriptor ./runtime-image/image.yaml build --dry-run docker
      - name: Check Image
        run: |
          ls -ltr target/image/Dockerfile
      - name: Checkout other repo
        uses: actions/checkout@v4
        with:
          repository: git@gitlab.cee.redhat.com:rnovelli/jboss-eap8-openjdk21-builder.git
          token: ${{ secrets.ACTIONS_GITLAB_TOKEN }}
          ref: jb-eap-8.1-rhel-9
          fetch-depth: 0
      - name: Potentially modify other repo files
        run : |
          ls -ltR
